# Generated by Django 4.0.6 on 2022-12-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
