# Generated by Django 4.0.6 on 2022-12-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0002_request_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='maintenance_status',
            field=models.BooleanField(default=False),
        ),
    ]
