# Generated by Django 4.0.6 on 2022-12-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0003_alter_elevator_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='maintenance_status',
            field=models.BooleanField(default=True),
        ),
    ]
